version: '3.9'
services: 
  redis:
    restart: always
    container_name: redis
    image: redis:6-alpine
    ports: 
      - '6379:6379'
  redisinsight:
    restart: always
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports: 
      - '8001:8001'

networks:
    local_cloud_env:
        driver: bridge
    cloud_network:
        driver: bridge